spring:
  application:
    name: diet_hub
  datasource:
    driver-class-name: org.h2.Driver # RDS ? ??? ?
    url: jdbc:h2:tcp://localhost/~/test # RDS ? ??? ?
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

jpa:
  hibernate:
    ddl-auto: create-drop
  open-in-view: false
  properties:
    hibernate:
      create_empty_composites:
        enabled: true
      format_sql: true
      default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQLDialect